%Callback function that displays the topic and message each time a new message is received.
function showMessage(topic,data)
global iii ...
    Corridorco2 Corridorhumidity Corridortemperature CorridortemperatureNN ...
    Room1co2 Room1humidity Room1temperature Room1temperatureNN ...
    Room2co2 Room2humidity Room2temperature Room2temperatureNN ...
    Room4co2 Room4humidity Room4temperature Room4temperatureNN ...
    Kitchenco2 Kitchenhumidity Kitchentemperature KitchentemperatureNN...
    Room1spT0 Room1spT1 ...
    KitchenspT0 KitchenspT1 ...
    CorridorspT0 CorridorspT1 ...
    myMQTT ...
    Room1extx Room1exty Room1nn_net ...
    Room2extx Room2exty Room2nn_net ...
    Room4extx Room4exty Room4nn_net ...
    Corridorextx Corridorexty Corridornn_net ...
    Kitchenextx Kitchenexty Kitchennn_net ...
    offset InletFlow DiffTemp OutsideTemp WindSpeed DirectSunPowerVertical ...
    jd
global RoomThermData RoomTempData RoomHumiData RoomCO2Data OutsideData DHeatingData flags

disp(topic);
%disp(data);
if contains(topic, '/0')

    RoomThermData=jsondecode(data);
    flags(1)=1;
end
if contains(topic, '/1')

    RoomTempData=jsondecode(data);
    flags(2)=1;

end
if contains(topic, '/2')

    RoomHumiData=jsondecode(data);
    flags(3)=1;

end
if contains(topic, '/3')

    RoomCO2Data=jsondecode(data);
    flags(4)=1;

end
if contains(topic, '/4')

    DHeatingData=jsondecode(data);
    flags(5)=1;

end
if contains(topic, '/5')

    OutsideData=jsondecode(data);
    flags(6)=1;

end

disp(flags);
xtimeNow= now;


if (all(flags))
    for iii=1:3
        xtime(iii)= xtimeNow+ RoomCO2Data(1).data(1).x;
        Room1co2(iii)= RoomCO2Data(1).data(1).y;
        Room1humidity(iii)= RoomHumiData(1).data(1).y;
        Room1temperature(iii)= RoomTempData(1).data(1).y;
        Room1temperatureNN(iii)= RoomTempData(1).data(1).y;


        Room2co2(iii)= RoomCO2Data(2).data(1).y;
        Room2humidity(iii)= RoomHumiData(2).data(1).y;
        Room2temperature(iii)= RoomTempData(2).data(1).y;
        Room2temperatureNN(iii)= RoomTempData(2).data(1).y;


        Room4co2(iii)= RoomCO2Data(3).data(1).y;
        Room4humidity(iii)= RoomHumiData(3).data(1).y;
        Room4temperature(iii)= RoomTempData(3).data(1).y;
        Room4temperatureNN(iii)= RoomTempData(3).data(1).y;


        Corridorco2(iii)= RoomCO2Data(4).data(1).y;
        Corridorhumidity(iii)= RoomHumiData(4).data(1).y;
        Corridortemperature(iii)= RoomTempData(4).data(1).y;
        CorridortemperatureNN(iii)= RoomTempData(4).data(1).y;

        Kitchenco2(iii)= RoomCO2Data(5).data(1).y;
        Kitchenhumidity(iii)= RoomHumiData(5).data(1).y;
        Kitchentemperature(iii)= RoomTempData(5).data(1).y;
        KitchentemperatureNN(iii)= RoomTempData(5).data(1).y;


        InletFlow(iii)= DHeatingData(1).data(1).y;
        DiffTemp(iii)= DHeatingData(2).data(1).y - DHeatingData(3).data(1).y;

        Room1spT0(iii)= RoomThermData(1).data(1).y;
        Room1spT1(iii)= RoomThermData(2).data(1).y;

        KitchenspT0(iii)= RoomThermData(3).data(1).y;
        KitchenspT1(iii)= RoomThermData(4).data(1).y;

        OutsideTemp(iii)= OutsideData(1).data(1).y;
        WindSpeed(iii)= OutsideData(2).data(1).y;
        DirectSunPowerVertical(iii)= OutsideData(3).data(1).y;

    end


    for iii=3:(length(RoomCO2Data(1).data)+2)

        Room1co2(iii)= RoomCO2Data(1).data(iii-2).y;
        Room1humidity(iii)= RoomHumiData(1).data(iii-2).y;
        Room1temperature(iii)= RoomTempData(1).data(iii-2).y;

        Room2co2(iii)= RoomCO2Data(2).data(iii-2).y;
        Room2humidity(iii)= RoomHumiData(2).data(iii-2).y;
        Room2temperature(iii)= RoomTempData(2).data(iii-2).y;

        Room4co2(iii)= RoomCO2Data(3).data(iii-2).y;
        Room4humidity(iii)= RoomHumiData(3).data(iii-2).y;
        Room4temperature(iii)= RoomTempData(3).data(iii-2).y;

        Corridorco2(iii)= RoomCO2Data(4).data(iii-2).y;
        Corridorhumidity(iii)= RoomHumiData(4).data(iii-2).y;
        Corridortemperature(iii)= RoomTempData(4).data(iii-2).y;

        Kitchenco2(iii)= RoomCO2Data(5).data(iii-2).y;
        Kitchenhumidity(iii)= RoomHumiData(5).data(iii-2).y;
        Kitchentemperature(iii)= RoomTempData(5).data(iii-2).y;


        InletFlow(iii)= DHeatingData(1).data(iii-2).y;
        DiffTemp(iii)= DHeatingData(2).data(iii-2).y - DHeatingData(3).data(iii-2).y;

        Room1spT0(iii)= RoomThermData(1).data(iii-2).y;
        Room1spT1(iii)= RoomThermData(2).data(iii-2).y;

        KitchenspT0(iii)= RoomThermData(3).data(iii-2).y;
        KitchenspT1(iii)= RoomThermData(4).data(iii-2).y;

        OutsideTemp(iii)= OutsideData(1).data(iii-2).y;
        WindSpeed(iii)= OutsideData(2).data(iii-2).y;
        DirectSunPowerVertical(iii)= OutsideData(3).data(iii-2).y;

    end

    iii=3;

    for iii=3:(length(RoomCO2Data(1).data)+2)

        Room1xin= [Room1temperatureNN(iii),  ...
            Room1temperatureNN(iii-2),  ...
            Room1humidity(iii),       ...
            Room1humidity(iii-2),     ...
            Room1co2(iii),     ...
            Room1co2(iii-2),     ...
            Corridortemperature(iii),    ...
            Corridortemperature(iii-2),  ...
            Corridorhumidity(iii),      ...
            Corridorhumidity(iii-2),   ...
            Corridorco2(iii),      ...
            Corridorco2(iii-2),   ...
            WindSpeed(iii),     ...
            WindSpeed(iii-2),     ...
            OutsideTemp(iii),     ...
            OutsideTemp(iii-2),     ...
            DirectSunPowerVertical(iii),     ...
            DirectSunPowerVertical(iii-2),     ...
            DiffTemp(iii),     ...
            DiffTemp(iii-2), ...
            InletFlow(iii),     ...
            InletFlow(iii-2),  ...
            Room1spT0(iii),  ...
            Room1spT1(iii)]';

        Room1xn= mapstd('apply',Room1xin,Room1extx);
        Room1TempN= Room1nn_net(Room1xn);
        Room1temperatureNN(iii+1)= mapstd('reverse',Room1TempN,Room1exty);
        disp(Room1temperatureNN(iii+1));

 Room2xin= [Room2temperatureNN(iii),  ...
                Room2temperatureNN(iii-2),  ...
                Corridortemperature(iii),    ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room1temperature(iii),       ...
                Room1temperature(iii-2),     ...
                Room1humidity(iii),       ...
                Room1humidity(iii-2),     ...
                Room1co2(iii),     ...
                Room1co2(iii-2),     ...
                Room2humidity(iii),       ...
                Room2humidity(iii-2),     ...
                Room2co2(iii),     ...
                Room2co2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';

            Room2xn= mapstd('apply',Room2xin,Room2extx);
            Room2TempN= Room2nn_net(Room2xn);
            Room2temperatureNN(iii+1)= mapstd('reverse',Room2TempN,Room2exty);

            %--Room4-----------------------------------------------------

            Room4xin= [Room4temperatureNN(iii),  ...
                Room4temperatureNN(iii-2),  ...
                Corridortemperature(iii),    ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room4humidity(iii),       ...
                Room4humidity(iii-2),     ...
                Room4co2(iii),     ...
                Room4co2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';

            Room4xn= mapstd('apply',Room4xin,Room4extx);
            Room4TempN= Room4nn_net(Room4xn);
            Room4temperatureNN(iii+1)= mapstd('reverse',Room4TempN,Room4exty);

            %--Corridor-----------------------------------------------------


            Corridorxin= [CorridortemperatureNN(iii),  ...
                CorridortemperatureNN(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room1temperature(iii),       ...
                Room1temperature(iii-2),       ...
                Room1humidity(iii),       ...
                Room1humidity(iii-2),     ...
                Room1co2(iii),     ...
                Room1co2(iii-2),     ...
                Kitchentemperature(iii),       ...
                Kitchentemperature(iii-2),       ...
                Kitchenhumidity(iii),       ...
                Kitchenhumidity(iii-2),     ...
                Kitchenco2(iii),     ...
                Kitchenco2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';   ...
%                CorridordiT0(iii),  ...
%                CorridordiT1(iii)]';

            Corridorxn= mapstd('apply',Corridorxin,Corridorextx);
            CorridorTempN= Corridornn_net(Corridorxn);
            CorridortemperatureNN(iii+1)= mapstd('reverse',CorridorTempN,Corridorexty);

            %--Kitchen-----------------------------------------------------

            Kitchenxin= [ KitchentemperatureNN(iii),       ...
                KitchentemperatureNN(iii-2),       ...
                Corridortemperature(iii),  ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Kitchenhumidity(iii),       ...
                Kitchenhumidity(iii-2),     ...
                Kitchenco2(iii),     ...
                Kitchenco2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2),   ...
                KitchenspT0(iii),  ...
                KitchenspT1(iii)]';

            Kitchenxn= mapstd('apply',Kitchenxin,Kitchenextx);
            KitchenTempN= Kitchennn_net(Kitchenxn);
            KitchentemperatureNN(iii+1)= mapstd('reverse',KitchenTempN,Kitchenexty);

            








    end
    flags= zeros(1,6);

    figure(1)
    dateaxis('x', 13)

    plot(Room1temperatureNN)
    title('Room1temperature')

    figure(2)
    plot(Room2temperatureNN)
    title('Room2temperature')

    figure(3)
    plot(Room4temperatureNN)
    title('Room4temperature')

    figure(4)
    plot(KitchentemperatureNN)
    title('Kitchentemperature')


    figure(5)
    plot(CorridortemperatureNN)
    title('Corridortemperature')



end