%Callback function that displays the topic and message each time a new message is received.
function showMessage(topic,data)
global iii ...
    Corridorco2 Corridorhumidity Corridortemperature CorridortemperatureNN ...
    Room1co2 Room1humidity Room1temperature Room1temperatureNN ...
    Room2co2 Room2humidity Room2temperature Room2temperatureNN ...
    Room4co2 Room4humidity Room4temperature Room4temperatureNN ...
    Kitchenco2 Kitchenhumidity Kitchentemperature KitchentemperatureNN...
    Room1diT0 Room1diT1 ...
    KitchendiT0 KitchendiT1 ...
    CorridordiT0 CorridordiT1 ...
    myMQTT ...
    Room1extx Room1exty Room1nn_net ...
    Room2extx Room2exty Room2nn_net ...
    Room4extx Room4exty Room4nn_net ...
    Corridorextx Corridorexty Corridornn_net ...
    Kitchenextx Kitchenexty Kitchennn_net ...
    offset InletFlow DiffTemp OutsideTemp WindSpeed DirectSunPowerVertical

disp(topic);
% disp(data);
if contains(topic, '2495/HouseModel')

    jd=jsondecode(data);
    %     %assignin('base','jsonData',jd);
    if isfield(jd.Rooms, 'Corridor')
        if isfield(jd.Rooms.Corridor, 'co2')

            % disp(jd.Rooms.Room1.thermostats(1).setpoint);

            Corridorco2(iii)= jd.Rooms.Corridor.co2;
            Corridorhumidity(iii)= jd.Rooms.Corridor.humidity;
            Corridortemperature(iii)= jd.Rooms.Corridor.temperature;

            Room1co2(iii)= jd.Rooms.Room1.co2;
            Room1humidity(iii)= jd.Rooms.Room1.humidity;
            Room1temperature(iii)= jd.Rooms.Room1.temperature;

            Room2co2(iii)= jd.Rooms.Room2.co2;
            Room2humidity(iii)= jd.Rooms.Room2.humidity;
            Room2temperature(iii)= jd.Rooms.Room2.temperature;

            Room4co2(iii)= jd.Rooms.Room4.co2;
            Room4humidity(iii)= jd.Rooms.Room4.humidity;
            Room4temperature(iii)= jd.Rooms.Room4.temperature;

            Kitchenco2(iii)= jd.Rooms.Kitchen.co2;
            Kitchenhumidity(iii)= jd.Rooms.Kitchen.humidity;
            Kitchentemperature(iii)= jd.Rooms.Kitchen.temperature;

            InletFlow(iii)= jd.InletFlow;
            DiffTemp(iii)= jd.InletTemperature - jd.OutletTemperature;

            Room1diT0(iii)= jd.Rooms.Room1.thermostats(1).setpoint - jd.Rooms.Room1.thermostats(1).temperature;
            Room1diT1(iii)= jd.Rooms.Room1.thermostats(2).setpoint - jd.Rooms.Room1.thermostats(2).temperature;

            KitchendiT0(iii)= jd.Rooms.Kitchen.thermostats(1).setpoint - jd.Rooms.Kitchen.thermostats(1).temperature;
            KitchendiT1(iii)= jd.Rooms.Kitchen.thermostats(2).setpoint - jd.Rooms.Kitchen.thermostats(2).temperature;

            CorridordiT0(iii)= jd.Rooms.Corridor.thermostats(1).setpoint - jd.Rooms.Corridor.thermostats(1).temperature;
            CorridordiT1(iii)= jd.Rooms.Corridor.thermostats(2).setpoint - jd.Rooms.Corridor.thermostats(2).temperature;


            OutsideTemp(iii)= OutsideTemp(iii-1);
            WindSpeed(iii)= WindSpeed(iii-1);
            DirectSunPowerVertical(iii)= DirectSunPowerVertical(iii-1);


            Room1xin= [Room1temperatureNN(iii),  ...
                Room1temperatureNN(iii-2),  ...
                Room1humidity(iii),       ...
                Room1humidity(iii-2),     ...
                Room1co2(iii),     ...
                Room1co2(iii-2),     ...
                Corridortemperature(iii),    ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2),  ...
                Room1diT0(iii),  ...
                Room1diT1(iii)]';

            Room1xn= mapstd('apply',Room1xin,Room1extx);
            Room1TempN= Room1nn_net(Room1xn);
            Room1temperatureNN(iii+1)= mapstd('reverse',Room1TempN,Room1exty);

            %--Room2-----------------------------------------------------

            Room2xin= [Room2temperatureNN(iii),  ...
                Room2temperatureNN(iii-2),  ...
                Corridortemperature(iii),    ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room1temperature(iii),       ...
                Room1temperature(iii-2),     ...
                Room1humidity(iii),       ...
                Room1humidity(iii-2),     ...
                Room1co2(iii),     ...
                Room1co2(iii-2),     ...
                Room2humidity(iii),       ...
                Room2humidity(iii-2),     ...
                Room2co2(iii),     ...
                Room2co2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';

            Room2xn= mapstd('apply',Room2xin,Room2extx);
            Room2TempN= Room2nn_net(Room2xn);
            Room2temperatureNN(iii+1)= mapstd('reverse',Room2TempN,Room2exty);

            %--Room4-----------------------------------------------------

            Room4xin= [Room4temperatureNN(iii),  ...
                Room4temperatureNN(iii-2),  ...
                Corridortemperature(iii),    ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room4humidity(iii),       ...
                Room4humidity(iii-2),     ...
                Room4co2(iii),     ...
                Room4co2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';

            Room4xn= mapstd('apply',Room4xin,Room4extx);
            Room4TempN= Room4nn_net(Room4xn);
            Room4temperatureNN(iii+1)= mapstd('reverse',Room4TempN,Room4exty);

            %--Corridor-----------------------------------------------------

            Corridorxin= [CorridortemperatureNN(iii),  ...
                CorridortemperatureNN(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room1temperature(iii),       ...
                Room1temperature(iii-2),       ...
                Room1humidity(iii),       ...
                Room1humidity(iii-2),     ...
                Room1co2(iii),     ...
                Room1co2(iii-2),     ...
                Kitchentemperature(iii),       ...
                Kitchentemperature(iii-2),       ...
                Kitchenhumidity(iii),       ...
                Kitchenhumidity(iii-2),     ...
                Kitchenco2(iii),     ...
                Kitchenco2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2),   ...
                CorridordiT0(iii),  ...
                CorridordiT1(iii)]';

            Corridorxn= mapstd('apply',Corridorxin,Corridorextx);
            CorridorTempN= Corridornn_net(Corridorxn);
            CorridortemperatureNN(iii+1)= mapstd('reverse',CorridorTempN,Corridorexty);

            %--Kitchen-----------------------------------------------------

            Kitchenxin= [ KitchentemperatureNN(iii),       ...
                KitchentemperatureNN(iii-2),       ...
                Corridortemperature(iii),  ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Kitchenhumidity(iii),       ...
                Kitchenhumidity(iii-2),     ...
                Kitchenco2(iii),     ...
                Kitchenco2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2),   ...
                KitchendiT0(iii),  ...
                KitchendiT1(iii)]';

            Kitchenxn= mapstd('apply',Kitchenxin,Kitchenextx);
            KitchenTempN= Kitchennn_net(Kitchenxn);
            KitchentemperatureNN(iii+1)= mapstd('reverse',KitchenTempN,Kitchenexty);

            dat.LocationId= 2495;
            dat.Time= floor(posixtime(datetime('now','TimeZone','local'))*1000+1000*60*10);
            dat.Rooms.Room1.temperatureNN= Room1temperatureNN(iii+1);
            dat.Rooms.Room2.temperatureNN= Room2temperatureNN(iii+1);
            dat.Rooms.Room4.temperatureNN= Room4temperatureNN(iii+1);
            dat.Rooms.Corridor.temperatureNN= CorridortemperatureNN(iii+1);
            dat.Rooms.Kitchen.temperatureNN= KitchentemperatureNN(iii+1);


            write(myMQTT,'domOS/2495/HouseModel',jsonencode(dat));
            iii= iii+1;
        end

    end
end
if contains(topic, '2495/Weather')
    jd=jsondecode(data);
    %assignin('base','jsonData',jd);
    if isfield(jd, 'values')
        %disp('weather');
        OutsideTemp(iii-1)= jd.nearest.Temperature.value;
        WindSpeed(iii-1)= jd.nearest.WindSpeed.value;
        DirectSunPowerVertical(iii-1)= jd.nearest.DirectSunPowerVertical.value;
    end
end
end
