%Callback function that displays the topic and message each time a new message is received.
function showMessage(topic,data)
global iii iii2 ...
    Corridorco2 Corridorhumidity Corridortemperature CorridortemperatureNN ...
    Room1co2 Room1humidity Room1temperature Room1temperatureNN ...
    Room2co2 Room2humidity Room2temperature Room2temperatureNN ...
    Room4co2 Room4humidity Room4temperature Room4temperatureNN ...
    Kitchenco2 Kitchenhumidity Kitchentemperature KitchentemperatureNN...
    Room1spT0 Room1spT1 ...
    KitchenspT0 KitchenspT1 ... 
    CorridorspT0 CorridorspT1 ...
    ER2RoomdiT0 ER2KitchendiT0 ER2KitchendiT1 ER2KitchendiT2 ...
    ER2Roomco2 ER2Roomhumidity ER2Roomtemperature ER2RoomtemperatureNN ...
    ER2Kitchenco2 ER2Kitchenhumidity ER2Kitchentemperature ER2KitchentemperatureNN...
    myMQTT ...
    Room1extx Room1exty Room1nn_net ...
    Room2extx Room2exty Room2nn_net ...
    Room4extx Room4exty Room4nn_net ...
    Corridorextx Corridorexty Corridornn_net ...
    Kitchenextx Kitchenexty Kitchennn_net ...
    ER2Roomextx ER2Roomexty ER2Roomnn_net ...
    ER2Kitchenextx ER2Kitchenexty ER2Kitchennn_net ...
    offset InletFlow DiffTemp ER2InletFlow ER2DiffTemp OutsideTemp WindSpeed DirectSunPowerVertical

disp(topic);
% disp(data);
if contains(topic, '2495/HouseModel')

    jd=jsondecode(data);
    %     %assignin('base','jsonData',jd);
    if isfield(jd.Rooms, 'Corridor')
        if isfield(jd.Rooms.Corridor, 'co2')

            Corridorco2(iii)= jd.Rooms.Corridor.co2;
            Corridorhumidity(iii)= jd.Rooms.Corridor.humidity;
            Corridortemperature(iii)= jd.Rooms.Corridor.temperature;

            Room1co2(iii)= jd.Rooms.Room1.co2;
            Room1humidity(iii)= jd.Rooms.Room1.humidity;
            Room1temperature(iii)= jd.Rooms.Room1.temperature;

            Room2co2(iii)= jd.Rooms.Room2.co2;
            Room2humidity(iii)= jd.Rooms.Room2.humidity;
            Room2temperature(iii)= jd.Rooms.Room2.temperature;

            Room4co2(iii)= jd.Rooms.Room4.co2;
            Room4humidity(iii)= jd.Rooms.Room4.humidity;
            Room4temperature(iii)= jd.Rooms.Room4.temperature;

            Kitchenco2(iii)= jd.Rooms.Kitchen.co2;
            Kitchenhumidity(iii)= jd.Rooms.Kitchen.humidity;
            Kitchentemperature(iii)= jd.Rooms.Kitchen.temperature;

            InletFlow(iii)= jd.InletFlow;
            DiffTemp(iii)= jd.InletTemperature - jd.OutletTemperature;

            Room1spT0(iii)= jd.Rooms.Room1.thermostats(1).setpoint;
            Room1spT1(iii)= jd.Rooms.Room1.thermostats(2).setpoint;

            KitchenspT0(iii)= jd.Rooms.Kitchen.thermostats(1).setpoint;
            KitchenspT1(iii)= jd.Rooms.Kitchen.thermostats(2).setpoint;

%             Room1diT0(iii)= jd.Rooms.Room1.thermostats(1).setpoint - jd.Rooms.Room1.thermostats(1).temperature;
%             Room1diT1(iii)= jd.Rooms.Room1.thermostats(2).setpoint - jd.Rooms.Room1.thermostats(2).temperature;
% 
%             KitchendiT0(iii)= jd.Rooms.Kitchen.thermostats(1).setpoint - jd.Rooms.Kitchen.thermostats(1).temperature;
%             KitchendiT1(iii)= jd.Rooms.Kitchen.thermostats(2).setpoint - jd.Rooms.Kitchen.thermostats(2).temperature;

            % CorridordiT0(iii)= jd.Rooms.Corridor.thermostats(1).setpoint - jd.Rooms.Corridor.thermostats(1).temperature;

%             if isfield(jd.Rooms.Corridor.thermostats(2),'temperature')
%                 disp(jd.Rooms.Corridor.thermostats(2).temperature);
%             else
%                 disp('Corridor no thero 2 temp');
%             end
%             if isfield(jd.Rooms.Corridor.thermostats(1),'temperature')
%                 disp(jd.Rooms.Corridor.thermostats(1).temperature);
%             else
%                 disp('Corridor no thero 1 temp');
%             end
% 
%             disp(jd.Rooms.Corridor.thermostats(1).temperature);
% 
% 
%             disp(jd.Rooms.Corridor.thermostats(2).setpoint);
% 
%             disp(jd.Rooms.Corridor.thermostats(1).setpoint);
% 
% 
%             CorridordiT1(iii)= jd.Rooms.Corridor.thermostats(2).setpoint - jd.Rooms.Corridor.thermostats(2).temperature;
% 
%                         CorridordiT0(iii)= CorridordiT1(iii);



            OutsideTemp(iii)= OutsideTemp(iii-1);
            WindSpeed(iii)= WindSpeed(iii-1);
            DirectSunPowerVertical(iii)= DirectSunPowerVertical(iii-1);


            Room1xin= [Room1temperatureNN(iii),  ...
                Room1temperatureNN(iii-2),  ...
                Room1humidity(iii),       ...
                Room1humidity(iii-2),     ...
                Room1co2(iii),     ...
                Room1co2(iii-2),     ...
                Corridortemperature(iii),    ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2),  ...
                Room1spT0(iii),  ...
                Room1spT1(iii)]';

            Room1xn= mapstd('apply',Room1xin,Room1extx);
            Room1TempN= Room1nn_net(Room1xn);
            Room1temperatureNN(iii+1)= mapstd('reverse',Room1TempN,Room1exty);
            disp(jd.Rooms.Room1.thermostats(1).setpoint);

            %--Room2-----------------------------------------------------




            Room2xin= [Room2temperatureNN(iii),  ...
                Room2temperatureNN(iii-2),  ...
                Room2humidity(iii),       ...
                Room2humidity(iii-2),     ...
                Room2co2(iii),     ...
                Room2co2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';

            Room2xn= mapstd('apply',Room2xin,Room2extx);
            Room2TempN= Room2nn_net(Room2xn);
            Room2temperatureNN(iii+1)= mapstd('reverse',Room2TempN,Room2exty);

            %--Room4-----------------------------------------------------

            Room4xin= [Room4temperatureNN(iii),  ...
                Room4temperatureNN(iii-2),  ...
                Corridortemperature(iii),    ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room4humidity(iii),       ...
                Room4humidity(iii-2),     ...
                Room4co2(iii),     ...
                Room4co2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';

            Room4xn= mapstd('apply',Room4xin,Room4extx);
            Room4TempN= Room4nn_net(Room4xn);
            Room4temperatureNN(iii+1)= mapstd('reverse',Room4TempN,Room4exty);

            %--Corridor-----------------------------------------------------


            Corridorxin= [CorridortemperatureNN(iii),  ...
                CorridortemperatureNN(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Room1temperature(iii),       ...
                Room1temperature(iii-2),       ...
                Room1humidity(iii),       ...
                Room1humidity(iii-2),     ...
                Room1co2(iii),     ...
                Room1co2(iii-2),     ...
                Kitchentemperature(iii),       ...
                Kitchentemperature(iii-2),       ...
                Kitchenhumidity(iii),       ...
                Kitchenhumidity(iii-2),     ...
                Kitchenco2(iii),     ...
                Kitchenco2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2)]';   ...
%                CorridordiT0(iii),  ...
%                CorridordiT1(iii)]';

            Corridorxn= mapstd('apply',Corridorxin,Corridorextx);
            CorridorTempN= Corridornn_net(Corridorxn);
            CorridortemperatureNN(iii+1)= mapstd('reverse',CorridorTempN,Corridorexty);

            %--Kitchen-----------------------------------------------------

            Kitchenxin= [ KitchentemperatureNN(iii),       ...
                KitchentemperatureNN(iii-2),       ...
                Corridortemperature(iii),  ...
                Corridortemperature(iii-2),  ...
                Corridorhumidity(iii),      ...
                Corridorhumidity(iii-2),   ...
                Corridorco2(iii),      ...
                Corridorco2(iii-2),   ...
                Kitchenhumidity(iii),       ...
                Kitchenhumidity(iii-2),     ...
                Kitchenco2(iii),     ...
                Kitchenco2(iii-2),     ...
                WindSpeed(iii),     ...
                WindSpeed(iii-2),     ...
                OutsideTemp(iii),     ...
                OutsideTemp(iii-2),     ...
                DirectSunPowerVertical(iii),     ...
                DirectSunPowerVertical(iii-2),     ...
                DiffTemp(iii),     ...
                DiffTemp(iii-2), ...
                InletFlow(iii),     ...
                InletFlow(iii-2),   ...
                KitchenspT0(iii),  ...
                KitchenspT1(iii)]';

            Kitchenxn= mapstd('apply',Kitchenxin,Kitchenextx);
            KitchenTempN= Kitchennn_net(Kitchenxn);
            KitchentemperatureNN(iii+1)= mapstd('reverse',KitchenTempN,Kitchenexty);

            dat.LocationId= 2495;
            dat.Time= floor(posixtime(datetime('now','TimeZone','local'))*1000+1000*60*10);
            dat.Rooms.Room1.temperatureNN= Room1temperatureNN(iii+1);
            dat.Rooms.Room2.temperatureNN= Room2temperatureNN(iii+1);
            dat.Rooms.Room4.temperatureNN= Room4temperatureNN(iii+1);
            dat.Rooms.Corridor.temperatureNN= CorridortemperatureNN(iii+1);
            dat.Rooms.Kitchen.temperatureNN= KitchentemperatureNN(iii+1);


            write(myMQTT,'domOS/2495/HouseModel',jsonencode(dat));
           iii= iii+1;
        end

    end
end
if contains(topic, '2494/HouseModel')
disp('inn1');

    jd=jsondecode(data);
    %     %assignin('base','jsonData',jd);
    if isfield(jd.Rooms, 'Room')
disp('inn2');
        if isfield(jd.Rooms.Room, 'co2')
disp('inn3');
       
            ER2Roomco2(iii2)= jd.Rooms.Room.co2;
            ER2Roomhumidity(iii2)= jd.Rooms.Room.humidity;
            ER2Roomtemperature(iii2)= jd.Rooms.Room.temperature;


            ER2Kitchenco2(iii2)= jd.Rooms.Kitchen.co2;
            ER2Kitchenhumidity(iii2)= jd.Rooms.Kitchen.humidity;
            ER2Kitchentemperature(iii2)= jd.Rooms.Kitchen.temperature;

            ER2InletFlow(iii2)= jd.InletFlow;
            ER2DiffTemp(iii2)= jd.InletTemperature - jd.OutletTemperature;

            ER2RoomdiT0(iii2)= jd.Rooms.Room.thermostats(1).setpoint - jd.Rooms.Room.thermostats(1).temperature;
            disp('inn1');


            ER2KitchendiT0(iii2)= jd.Rooms.Kitchen.thermostats(1).setpoint - jd.Rooms.Kitchen.thermostats(1).temperature;
            ER2KitchendiT1(iii2)= jd.Rooms.Kitchen.thermostats(2).setpoint - jd.Rooms.Kitchen.thermostats(2).temperature;
            ER2KitchendiT2(iii2)= jd.Rooms.Kitchen.thermostats(3).setpoint - jd.Rooms.Kitchen.thermostats(3).temperature;
            disp('inn2');

            OutsideTemp(iii2)= OutsideTemp(iii2-1);
            WindSpeed(iii2)= WindSpeed(iii2-1);
            DirectSunPowerVertical(iii2)= DirectSunPowerVertical(iii2-1);
                        disp('inn3');


            ER2Roomxin= [ER2RoomtemperatureNN(iii2),  ...
                ER2RoomtemperatureNN(iii2-2),  ...
                ER2Roomhumidity(iii2),       ...
                ER2Roomhumidity(iii2-2),     ...
                ER2Roomco2(iii2),     ...
                ER2Roomco2(iii2-2),     ...
                ER2Kitchentemperature(iii2),       ...
                ER2Kitchentemperature(iii2-2),       ...
                ER2Kitchenhumidity(iii2),       ...
                ER2Kitchenhumidity(iii2-2),     ...
                ER2Kitchenco2(iii2),     ...
                ER2Kitchenco2(iii2-2),     ...
                WindSpeed(iii-1),    ...
                WindSpeed(iii-3),    ...
                OutsideTemp(iii-1),    ...
                OutsideTemp(iii-3),    ...
                DirectSunPowerVertical(iii-1),     ...
                DirectSunPowerVertical(iii-3),  ...
                ER2DiffTemp(iii2),     ...
                ER2DiffTemp(iii2-2),  ...
                ER2InletFlow(iii2),   ...
                ER2InletFlow(iii2-2),  ...
                ER2RoomdiT0(iii2)]';

                                    disp('inn4');


          
            ER2Roomxn= mapstd('apply',ER2Roomxin,ER2Roomextx);


            ER2RoomTempN= ER2Roomnn_net(ER2Roomxn);
            ER2RoomtemperatureNN(iii2+1)= mapstd('reverse',ER2RoomTempN,ER2Roomexty);

                                    disp('inn5');

            %--Kitchen-----------------------------------------------------

            ER2Kitchenxin= [ ER2KitchentemperatureNN(iii2),       ...
                ER2KitchentemperatureNN(iii2-2),       ...
                ER2Kitchenhumidity(iii2),       ...
                ER2Kitchenhumidity(iii2-2),     ...
                ER2Kitchenco2(iii2),     ...
                ER2Kitchenco2(iii2-2),     ...
                ER2Roomtemperature(iii2),  ...
                ER2Roomtemperature(iii2-2),  ...
                ER2Roomhumidity(iii2),       ...
                ER2Roomhumidity(iii2-2),     ...
                ER2Roomco2(iii2),     ...
                ER2Roomco2(iii2-2),     ...
                 WindSpeed(iii-1),    ...
                WindSpeed(iii-3),    ...
                OutsideTemp(iii-1),    ...
                OutsideTemp(iii-3),    ...
                DirectSunPowerVertical(iii-1),     ...
                DirectSunPowerVertical(iii-3),    ...
                DiffTemp(iii2),     ...
                DiffTemp(iii2-2), ...
                InletFlow(iii2),     ...
                InletFlow(iii2-2),   ...
                ER2KitchendiT0(iii2),  ...
                ER2KitchendiT1(iii2),  ...
                ER2KitchendiT2(iii2)]';

            ER2Kitchenxn= mapstd('apply',ER2Kitchenxin,ER2Kitchenextx);
            ER2KitchenTempN= ER2Kitchennn_net(ER2Kitchenxn);
            ER2KitchentemperatureNN(iii2+1)= mapstd('reverse',ER2KitchenTempN,ER2Kitchenexty);

            dat2.LocationId= 2494;
            dat2.Time= floor(posixtime(datetime('now','TimeZone','local'))*1000+1000*60*10);
            dat2.Rooms.Room.temperatureNN= ER2RoomtemperatureNN(iii2+1);
            dat2.Rooms.Kitchen.temperatureNN= ER2KitchentemperatureNN(iii2+1);


            write(myMQTT,'domOS/2494/HouseModel',jsonencode(dat2));
            iii2= iii2+1;
        end

    end
end
          

if contains(topic, '2495/Weather')
    jd=jsondecode(data);
    %assignin('base','jsonData',jd);
    if isfield(jd, 'values')
        %disp('weather');
        OutsideTemp(iii-1)= jd.nearest.Temperature.value;
        WindSpeed(iii-1)= jd.nearest.WindSpeed.value;
        DirectSunPowerVertical(iii-1)= jd.nearest.DirectSunPowerVertical.value;
    end
end
end
